Repository Body-Buddy/BodyBuddy-BE, pull requests merged in 2023-09, with the labels that each got.

#30 refactor: 채팅기능 개선 + 채팅방 CRUD 구현
  src/main/java/com/bb3/bodybuddybe/chat/advice/SessionManager.java
  src/main/java/com/bb3/bodybuddybe/chat/advice/WebSocketHandler.java
  src/main/java/com/bb3/bodybuddybe/chat/controller/ChatController.java
  src/main/java/com/bb3/bodybuddybe/chat/dto/ChatResponseDto.java
  src/main/java/com/bb3/bodybuddybe/chat/dto/MessageRequestDto.java
  src/main/java/com/bb3/bodybuddybe/chat/dto/MessageResponseDto.java
  src/main/java/com/bb3/bodybuddybe/chat/entity/Chat.java
  src/main/java/com/bb3/bodybuddybe/chat/entity/Message.java
  src/main/java/com/bb3/bodybuddybe/chat/entity/MessageType.java
  src/main/java/com/bb3/bodybuddybe/chat/entity/UserChat.java
  src/main/java/com/bb3/bodybuddybe/chat/repository/ChatRepository.java
  src/main/java/com/bb3/bodybuddybe/chat/repository/GroupChatMemberRepository.java
  src/main/java/com/bb3/bodybuddybe/chat/repository/UserChatRepository.java
  src/main/java/com/bb3/bodybuddybe/chat/service/ChatService.java
  src/main/java/com/bb3/bodybuddybe/common/exception/ErrorCode.java
  src/main/java/com/bb3/bodybuddybe/user/entity/User.java
Labels: Feature 🎨, Refactor ⚙️

#34 fix: 버그 수정 및 변경된 요구사항 반영
  src/main/java/com/bb3/bodybuddybe/comment/dto/CommentResponseDto.java
  src/main/java/com/bb3/bodybuddybe/common/config/CorsConfig.java
  src/main/java/com/bb3/bodybuddybe/common/config/WebConfig.java
  src/main/java/com/bb3/bodybuddybe/common/config/WebSecurityConfig.java
  src/main/java/com/bb3/bodybuddybe/common/security/JwtAuthenticationFilter.java
  src/main/java/com/bb3/bodybuddybe/common/security/JwtAuthorizationFilter.java
  src/main/java/com/bb3/bodybuddybe/common/security/UserDetailsImpl.java
  src/main/java/com/bb3/bodybuddybe/common/security/UserDetailsServiceImpl.java
  src/main/java/com/bb3/bodybuddybe/like/dto/LikeCommentResponseDto.java
  src/main/java/com/bb3/bodybuddybe/like/dto/LikePostResponseDto.java
  src/main/java/com/bb3/bodybuddybe/user/dto/LoginResponseDto.java
  src/main/java/com/bb3/bodybuddybe/user/entity/User.java
  src/main/java/com/bb3/bodybuddybe/user/repository/UserRepository.java
  src/main/java/com/bb3/bodybuddybe/user/service/UserServiceImpl.java
  src/test/java/com/bb3/bodybuddybe/user/service/UserServiceImplTest.java
Labels: Bug 🐞, Feature 🎨

#38 refactor: CommentService 추상화
  src/main/java/com/bb3/bodybuddybe/comment/controller/CommentController.java
  src/main/java/com/bb3/bodybuddybe/comment/service/CommentService.java
  src/main/java/com/bb3/bodybuddybe/comment/service/CommentServiceImpl.java
Labels: Refactor ⚙️

#41 hotfix: 로그인 시 인증 헤더가 없는 문제 해결
  src/main/java/com/bb3/bodybuddybe/common/config/WebSecurityConfig.java
Labels: Hotfix 🖊

#42 Feature: 소셜 로그인 및 토큰 분리
  .gitignore
  build.gradle
  src/main/java/com/bb3/bodybuddybe/common/config/WebSecurityConfig.java
  src/main/java/com/bb3/bodybuddybe/common/jwt/JwtUtil.java
  src/main/java/com/bb3/bodybuddybe/common/oauth2/CustomOAuth2UserService.java
  src/main/java/com/bb3/bodybuddybe/common/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/bb3/bodybuddybe/common/oauth2/dto/OAuthAttributes.java
  src/main/java/com/bb3/bodybuddybe/common/oauth2/entity/RefreshToken.java
  src/main/java/com/bb3/bodybuddybe/common/oauth2/repository/RefreshTokenRepository.java
  src/main/java/com/bb3/bodybuddybe/common/security/JwtAuthenticationFilter.java
  src/main/java/com/bb3/bodybuddybe/common/security/JwtAuthorizationFilter.java
  src/main/java/com/bb3/bodybuddybe/common/security/UserDetailsImpl.java
  src/main/java/com/bb3/bodybuddybe/common/security/UserDetailsServiceImpl.java
  src/main/java/com/bb3/bodybuddybe/matching/controller/MatchingController.java
  src/main/java/com/bb3/bodybuddybe/matching/repository/MatchingCriteriaRepository.java
  src/main/java/com/bb3/bodybuddybe/user/controller/UserController.java
  src/main/java/com/bb3/bodybuddybe/user/dto/ChangedPasswordRequestDto.java
  src/main/java/com/bb3/bodybuddybe/user/entity/User.java
  src/main/java/com/bb3/bodybuddybe/user/repository/UserRepository.java
  src/main/java/com/bb3/bodybuddybe/user/service/EmailService.java
  src/main/java/com/bb3/bodybuddybe/user/service/EmailServiceImpl.java
  src/main/java/com/bb3/bodybuddybe/user/service/UserService.java
  src/main/java/com/bb3/bodybuddybe/user/service/UserServiceImpl.java
  src/main/resources/application.properties
Labels: Feature 🎨

#44 feat: 1대1 채팅 생성 또는 가져오기
  src/main/java/com/bb3/bodybuddybe/chat/controller/ChatController.java
  src/main/java/com/bb3/bodybuddybe/chat/dto/ChatRequestDto.java
  src/main/java/com/bb3/bodybuddybe/chat/dto/ChatResponseDto.java
  src/main/java/com/bb3/bodybuddybe/chat/entity/Chat.java
  src/main/java/com/bb3/bodybuddybe/chat/repository/ChatRepository.java
  src/main/java/com/bb3/bodybuddybe/chat/service/ChatService.java
Labels: Feature 🎨

#45 bug: user 엔티티 수정
  src/main/java/com/bb3/bodybuddybe/common/config/WebSecurityConfig.java
  src/main/java/com/bb3/bodybuddybe/common/oauth2/entity/LogoutList.java
  src/main/java/com/bb3/bodybuddybe/common/oauth2/repository/LogoutlistRepository.java
  src/main/java/com/bb3/bodybuddybe/common/security/JwtAuthorizationFilter.java
  src/main/java/com/bb3/bodybuddybe/user/controller/UserController.java
  src/main/java/com/bb3/bodybuddybe/user/dto/SocialUpdateInform.java
  src/main/java/com/bb3/bodybuddybe/user/entity/User.java
  src/main/java/com/bb3/bodybuddybe/user/service/UserService.java
  src/main/java/com/bb3/bodybuddybe/user/service/UserServiceImpl.java
Labels: Bug 🐞, Feature 🎨

#46 fix: ChatRepository Query method 오류 수정
  src/main/java/com/bb3/bodybuddybe/chat/repository/ChatRepository.java
  src/main/java/com/bb3/bodybuddybe/chat/service/ChatService.java
Labels: Bug 🐞, Hotfix 🖊

#47 feat: 게시글 이미지 등록
  src/main/java/com/bb3/bodybuddybe/common/config/ImageConfig.java
  src/main/java/com/bb3/bodybuddybe/common/exception/ErrorCode.java
  src/main/java/com/bb3/bodybuddybe/image/entity/Image.java
  src/main/java/com/bb3/bodybuddybe/image/repository/ImageRepository.java
  src/main/java/com/bb3/bodybuddybe/post/controller/PostController.java
  src/main/java/com/bb3/bodybuddybe/post/dto/PostCreateRequestDto.java
  src/main/java/com/bb3/bodybuddybe/post/dto/PostResponseDto.java
  src/main/java/com/bb3/bodybuddybe/post/service/PostService.java
  src/main/java/com/bb3/bodybuddybe/post/service/PostServiceImpl.java
  src/main/java/com/bb3/bodybuddybe/user/entity/User.java
  src/main/resources/application.properties
  src/test/java/com/bb3/bodybuddybe/user/service/UserServiceImplTest.java
Labels: Feature 🎨

#49 feat: 알림 기능 SSE 구독 구현
  src/main/java/com/bb3/bodybuddybe/common/exception/ErrorCode.java
  src/main/java/com/bb3/bodybuddybe/notification/controller/NotificationController.java
  src/main/java/com/bb3/bodybuddybe/notification/dto/NotificationListResponseDto.java
  src/main/java/com/bb3/bodybuddybe/notification/dto/NotificationRequestDto.java
  src/main/java/com/bb3/bodybuddybe/notification/dto/NotificationResponseDto.java
  src/main/java/com/bb3/bodybuddybe/notification/entity/Notification.java
  src/main/java/com/bb3/bodybuddybe/notification/entity/NotificationType.java
  src/main/java/com/bb3/bodybuddybe/notification/repository/EmitterRepository.java
  src/main/java/com/bb3/bodybuddybe/notification/repository/EmitterRepositoryImpl.java
  src/main/java/com/bb3/bodybuddybe/notification/repository/NotificationRepository.java
  src/main/java/com/bb3/bodybuddybe/notification/service/NotificationService.java
  src/main/java/com/bb3/bodybuddybe/notification/service/NotificationServiceImpl.java
Labels: Feature 🎨

#51 feat: WebSocket STOMP적용
  build.gradle
  src/main/java/com/bb3/bodybuddybe/chat/advice/WebSocketHandler.java
  src/main/java/com/bb3/bodybuddybe/chat/config/StompWebSocketConfig.java
  src/main/java/com/bb3/bodybuddybe/chat/config/WebSocketConfig.java
  src/main/java/com/bb3/bodybuddybe/chat/controller/ChatController.java
  src/main/java/com/bb3/bodybuddybe/chat/controller/MessageController.java
  src/main/java/com/bb3/bodybuddybe/chat/dto/MessageDto.java
  src/main/java/com/bb3/bodybuddybe/chat/dto/MessageRequestDto.java
  src/main/java/com/bb3/bodybuddybe/chat/dto/MessageResponseDto.java
  src/main/java/com/bb3/bodybuddybe/chat/entity/Message.java
  src/main/java/com/bb3/bodybuddybe/chat/service/ChatService.java
  src/main/java/com/bb3/bodybuddybe/chat/service/MessageService.java
  src/main/java/com/bb3/bodybuddybe/common/exception/ErrorCode.java
Labels: Feature 🎨

#55 feat: 게시글 동영상 등록
  src/main/java/com/bb3/bodybuddybe/user/entity/User.java
  src/main/resources/application.properties
Labels: Feature 🎨

#60 fix: ChatService.getOrCreateDirectChatRoom() 오류수정
  README.md
  src/main/java/com/bb3/bodybuddybe/chat/controller/MessageController.java
  src/main/java/com/bb3/bodybuddybe/chat/dto/ChatRequestDto.java
  src/main/java/com/bb3/bodybuddybe/chat/repository/ChatRepository.java
  src/main/java/com/bb3/bodybuddybe/chat/service/ChatService.java
Labels: Bug 🐞, Hotfix 🖊

#65 docs: readme 작성
  README.md
Labels: Documentation 📖

#67 hotfix: 테스트 실패 오류 해결
  src/main/java/com/bb3/bodybuddybe/chat/service/ChatService.java
  src/main/java/com/bb3/bodybuddybe/gym/service/GymServiceImpl.java
  src/main/java/com/bb3/bodybuddybe/gym/service/KakaoApiClient.java
  src/test/java/com/bb3/bodybuddybe/BodyBuddyBeApplicationTests.java
  src/test/java/com/bb3/bodybuddybe/gym/service/GymServiceImplTest.java
  src/test/java/com/bb3/bodybuddybe/matching/service/MatchingServiceImplTest.java
  src/test/java/com/bb3/bodybuddybe/user/service/UserServiceImplTest.java
Labels: Test 🧪, Hotfix 🖊

#56 feat: 댓글, 좋아요 알림
  src/main/java/com/bb3/bodybuddybe/comment/service/CommentServiceImpl.java
  src/main/java/com/bb3/bodybuddybe/notification/config/AsyncConfig.java
  src/main/java/com/bb3/bodybuddybe/notification/dto/NotificationRequestDto.java
  src/main/java/com/bb3/bodybuddybe/notification/dto/NotificationResponseDto.java
  src/main/java/com/bb3/bodybuddybe/notification/entity/Notification.java
  src/main/java/com/bb3/bodybuddybe/notification/entity/NotificationType.java
  src/main/java/com/bb3/bodybuddybe/notification/service/NotificationService.java
  src/main/java/com/bb3/bodybuddybe/notification/service/NotificationServiceImpl.java
Labels: Feature 🎨
